"""empty message

Revision ID: a68a20d29b5d
Revises: 
Create Date: 2020-08-21 03:47:02.743936+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a68a20d29b5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_request",
        sa.Column("user_request_id", sa.Integer(), nullable=False),
        sa.Column("api_method", sa.String(length=32), nullable=False),
        sa.Column("api_endpoint", sa.String(length=1024), nullable=False),
        sa.Column("request_body", sa.String(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_request_id"),
    )
    op.create_table(
        "user_session",
        sa.Column("user_session_id", sa.Integer(), nullable=False),
        sa.Column("user_token", sa.String(length=128), nullable=False),
        sa.Column("access_token", sa.String(length=128), nullable=False),
        sa.Column("refresh_token", sa.String(length=128), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_session_id"),
        sa.UniqueConstraint("user_token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_session")
    op.drop_table("user_request")
    # ### end Alembic commands ###
