"""empty message

Revision ID: adf2bbc26bd0
Revises: a68a20d29b5d
Create Date: 2020-08-24 12:10:27.722517+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adf2bbc26bd0"
down_revision = "a68a20d29b5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "user_session_access_token_refresh_token_key",
        "user_session",
        ["access_token", "refresh_token"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_session_access_token_refresh_token_key",
        "user_session",
        type_="unique",
    )
    # ### end Alembic commands ###
