#!/bin/bash

set -euo pipefail

export CELERY_WORKER_NAME=${CELERY_WORKER_NAME:-"worker@%h"}
export CELERY_WORKER_QUEUE=${CELERY_WORKER_QUEUE:-"token"}
export CELERY_WORKER_POOL=${CELERY_WORKER_POOL:-"prefork"}
export CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-"1"}
export CELERY_WORKER_MAX_MEMORY_PER_CHILD=${CELERY_WORKER_MAX_MEMORY_PER_CHILD:-"131072"}
export CELERY_WORKER_MAX_TASKS_PER_CHILD=${CELERY_WORKER_MAX_TASKS_PER_CHILD:-"1000"}
export CELERY_WORKER_LOGLEVEL=${CELERY_WORKER_LOGLEVEL:-"warning"}

exec celery \
    worker \
    -A "$@" \
    -n "${CELERY_WORKER_NAME}" \
    -Q "${CELERY_WORKER_QUEUE}" \
    -P "${CELERY_WORKER_POOL}" \
    -c "${CELERY_WORKER_CONCURRENCY}" \
    --max-memory-per-child "${CELERY_WORKER_MAX_MEMORY_PER_CHILD}" \
    --max-tasks-per-child "${CELERY_WORKER_MAX_TASKS_PER_CHILD}" \
    -l "${CELERY_WORKER_LOGLEVEL}"